//open the scrCheckRoom script

var f;
f = file_text_open_write(global.scriptDir + '\scrCheckRoom.gml');

/*
switch (room){
    case r1_1:
    case r1_...:
    ...
    case ri_n:return i;
    
    case rj_n:return j;
    ...
    default:return 0;
}
}
*/

writeWithBreak(f,"///scrCheckRoom(room)");
writeWithBreak(f,"//generated by convertor, if you edit it by hand then you do so at your own risk!");
writeWithBreak(f,"switch(room){");

var tab,tabNum,tempString;
tab = "    ";
tabNum = 0;

var stageValue,mapList,map;
tabLog()
var i,folder;
/*
for(folder = ds_map_find_first(global.jmapMap);
    ds_map_exists(global.jmapMap,folder); 
    folder = ds_map_find_next(global.jmapMap,folder)){
    */
    //show_message("stageValue: " + string_digits(folder));
for (i = 0; i < ds_map_size(global.jmapMap); i += 1){
    folder = 's' + string(i + 1);
    roomList = ds_map_find_value(global.jmapMap,folder);
    if(ds_map_size(roomList) > 0){
        addLog(folder + ": processing " + string(ds_map_size(roomList)) + " rooms");
        var j,map;
        /*
        for(map = ds_map_find_first(roomList);
            ds_map_exists(roomList,map);
            map = ds_map_find_next(roomList,map)){
            */
        for (j = 0; j < ds_map_size(roomList); j += 1){
            map = 'r' + string(i + 1) + '_' + string(j + 1);
            //case ri_j:
            tabNum = 1;
            tempString = "";
            repeat(tabNum)tempString += tab;
            tempString += "case " + map + ":";
            writeWithBreak(f,tempString);
            
        }
        tabNum = 2;
        //return [stageValue]
        tempString = "";
        repeat(tabNum)tempString += tab;
        tempString += "return " + string_digits(folder) + ";";
        writeWithBreak(f,tempString);
        tabNum = 0;
    }
    else {
        addLog(folder + ": this stage has no rooms");
    }
}
resetLog();

writeWithBreak(f,"    default: return 0;");
writeWithBreak(f,"}");

file_text_close(f);

//add content
//exit
